name: Release

on:
  release:
    types: [published]

jobs:
  create-archive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate Archive name
      id: archive-name
      run: echo ::set-output name=filename::CorsairLightingProtocolBoards-${GITHUB_REF#refs/tags/}.zip
    - name: Create archive
      env:
        ARCHIVE_FILE: ${{ steps.archive-name.outputs.filename }}
      run: |
        mv avr CorsairLightingProtocolBoards
        zip -r "$ARCHIVE_FILE" CorsairLightingProtocolBoards
    - name: Get upload url
      id: release-id
      run: |
        RELEASE_ID=$(jq --raw-output '.release.id' $GITHUB_EVENT_PATH)
        echo "::set-output name=upload_url::https://uploads.github.com/repos/${GITHUB_REPOSITORY}/releases/${RELEASE_ID}/assets{?name,label}"
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.release-id.outputs.upload_url }}
        asset_path: ${{ steps.archive-name.outputs.filename }}
        asset_name: ${{ steps.archive-name.outputs.filename }}
        asset_content_type: application/zip
    - name: Print package metadata
      env:
        ARCHIVE_URL: ${{ steps.upload-release-asset.outputs.browser_download_url }}
        ARCHIVE_FILE: ${{ steps.archive-name.outputs.filename }}
      run: |
        echo url: "$ARCHIVE_URL"
        echo archiveFileName: "$ARCHIVE_FILE"
        echo checksum: SHA-256:$(sha256sum $ARCHIVE_FILE | cut -f1 -d ' ')
        echo size: $(stat -c%s $ARCHIVE_FILE)
